CREATE MATERIALIZED VIEW STAGE AS (
SELECT 
    A1.CAS_ID,
    A1.CAS_DATA_NOTIFICACAO,
    A1.CAS_DATA_PRIMEIROS_SINTOMAS,
    A2.MUN_NOME,
    A3.UNI_NOME,
    A1.CAS_ESTRANGEIRO,
    GENERO.GEN_DESCRICAO,
    A1.CAS_DATA_NASCIMENTO,
    IDADES_GESTACIONAIS.IDG_DESCRICAO,
    RACAS.RAC_NOME,
    ESCOLARIDADES.ESC_DESCRICAO,
    ZONAS.ZON_DESCRICAO,
    A1.CAS_NOSOCOMIAL,
    NVL2(UTI_CAS_ID, 'Sim','Não') AS UTI,
    SUPORTE_VENTILADOR.SVE_DESCRICAO,
    CLASSIFICACOES.CLA_DESC,
    A1.CAS_DATA_DIGITACAO,
    TRABALHA_ANIMAIS.TAN_DESCRICAO,
    A8.EVO_DESC,
    A2.QUANTIDADE_CASOS_MUNICIPIO,
    A3.QTD_CASOS_UNIDADE,
    NVL2(A4.QTD_DIAS_VAC_COVID, TO_CHAR(A4.QTD_DIAS_VAC_COVID), 'Caso não vacinado contra covid antes dos primeiros sintomas') AS QTD_DIAS_VAC_COVID,
    NVL2(A5.QTD_VAC_GRIPE_DIAS, TO_CHAR(A5.QTD_VAC_GRIPE_DIAS), 'Não há reporte de vacina da gripe antes dos primeiros sintomas') AS QTD_VAC_GRIPE_DIAS,
    NVL2(A6.DIAS_DO_CASO, TO_CHAR(A6.DIAS_DO_CASO), 'Não foi informado a data de evolução final do caso') AS DIAS_DO_CASO,
    NVL(A7.QTD_VACINAS_COVID, 0) AS QTD_VACINAS_COVID
FROM (
    SELECT 
        CAS_ID,
        CAS_DATA_NOTIFICACAO,
        CAS_DATA_PRIMEIROS_SINTOMAS,
        CAS_ESTRANGEIRO,
        CAS_GEN_ID,
        CAS_DATA_NASCIMENTO,
        CAS_IDG_ID,
        CAS_RAC_ID,
        CAS_ESC_ID,
        CAS_ZON_ID,
        CAS_NOSOCOMIAL,
        CAS_SVE_ID,
        CAS_CLA_ID,
        CAS_DATA_DIGITACAO,
        CAS_TAN_ID
    FROM CASOS 
    UNION 
    SELECT 
        CAS_ID,
        CAS_DATA_NOTIFICACAO,
        CAS_DATA_PRIMEIROS_SINTOMAS,
        CAS_ESTRANGEIRO,
        CAS_GEN_ID,
        CAS_DATA_NASCIMENTO,
        CAS_IDG_ID,
        CAS_RAC_ID,
        CAS_ESC_ID,
        CAS_ZON_ID,
        CAS_NOSOCOMIAL,
        CAS_SVE_ID,
        CAS_CLA_ID,
        CAS_DATA_DIGITACAO,
        CAS_TAN_ID
    FROM H_CASOS
    ) A1
LEFT JOIN (
    SELECT 
        CAS_ID,
        QUANTIDADE_CASOS_MUNICIPIO,
        MUN_NOME
    FROM (SELECT CAS_ID, CAS_MUN_ID FROM CASOS UNION SELECT CAS_ID, CAS_MUN_ID FROM H_CASOS) B1
    LEFT JOIN (
        SELECT 
            COUNT(CAS_ID) AS QUANTIDADE_CASOS_MUNICIPIO,
            CAS_MUN_ID
        FROM (SELECT CAS_ID, CAS_MUN_ID FROM CASOS UNION SELECT CAS_ID, CAS_MUN_ID FROM H_CASOS)
        GROUP BY CAS_MUN_ID
    ) B2 ON B1.CAS_MUN_ID = B2.CAS_MUN_ID
    LEFT JOIN MUNICIPIOS ON B1.CAS_MUN_ID = MUN_ID
) A2 ON A1.CAS_ID =  A2.CAS_ID
LEFT JOIN (
    SELECT 
        C1.CAS_ID AS CAS_ID,
        C1.CAS_UNI_ID,
        QTD_CASOS_UNIDADE,
        UNI_NOME
    FROM (SELECT CAS_ID, CAS_UNI_ID FROM CASOS UNION SELECT CAS_ID, CAS_UNI_ID FROM H_CASOS) C1
    LEFT JOIN (
        SELECT 
            CAS_UNI_ID,
            COUNT(CAS_ID) AS QTD_CASOS_UNIDADE
        FROM (SELECT CAS_ID, CAS_UNI_ID FROM CASOS UNION SELECT CAS_ID, CAS_UNI_ID FROM H_CASOS) 
        GROUP BY CAS_UNI_ID
    ) C2 ON C1.CAS_UNI_ID =  C2.CAS_UNI_ID
    LEFT JOIN UNIDADES C3 ON C1.CAS_UNI_ID = UNI_ID
) A3 ON A1.CAS_ID = A3.CAS_ID
LEFT JOIN (
    SELECT
        CAS_ID,
        MIN(QTD_DIAS_VAC_COVID) AS QTD_DIAS_VAC_COVID
    FROM (
        SELECT 
            CAS_ID,
            VAC_DATA_APLICACAO,
            CAS_DATA_PRIMEIROS_SINTOMAS,
            CAS_DATA_PRIMEIROS_SINTOMAS - VAC_DATA_APLICACAO  AS QTD_DIAS_VAC_COVID -- calculo da diferenÃ§a em dias
        FROM (
            SELECT * FROM ( SELECT VAC_CAS_ID, VAC_DATA_APLICACAO FROM H_VACINAS_COVID UNION SELECT VAC_CAS_ID, VAC_DATA_APLICACAO FROM VACINAS_COVID )
            WHERE VAC_DATA_APLICACAO > '25/01/20' -- Impedir dados inconsistentes!
        ) -- Retona o id do casos e a data de sua ultima vacina
        LEFT JOIN (SELECT CAS_ID, CAS_DATA_PRIMEIROS_SINTOMAS FROM H_CASOS UNION SELECT CAS_ID, CAS_DATA_PRIMEIROS_SINTOMAS FROM CASOS) -- Uso de usign para unir histÃ³rico com corrente
        ON VAC_CAS_ID = CAS_ID
        WHERE CAS_DATA_PRIMEIROS_SINTOMAS - VAC_DATA_APLICACAO  > 0 -- Evita casos em que a vacinacao ocorreu ante do inicio dos sintomas ou a vacinaÃ§Ã£o ocorreu no mesmo dia do inicio dos sintomas
        ) 
    GROUP BY CAS_ID
) A4 ON A1.CAS_ID = A4.CAS_ID
LEFT JOIN (
    SELECT 
        CAS_ID,
        VAG_DATA,
        CAS_DATA_PRIMEIROS_SINTOMAS,
        CAS_DATA_PRIMEIROS_SINTOMAS - VAG_DATA  AS QTD_VAC_GRIPE_DIAS -- calculo da diferenÃ§a em dias
    FROM ( SELECT VAG_CAS_ID, VAG_DATA FROM H_VACINAS_GRIPE UNION SELECT VAG_CAS_ID, VAG_DATA FROM VACINAS_GRIPE )  -- Retona o id do casos e a data de sua ultima vacina
    LEFT JOIN (SELECT CAS_ID, CAS_DATA_PRIMEIROS_SINTOMAS FROM H_CASOS UNION SELECT CAS_ID, CAS_DATA_PRIMEIROS_SINTOMAS FROM CASOS) -- Uso de usign para unir histÃ³rico com corrente
    ON VAG_CAS_ID = CAS_ID
    WHERE CAS_DATA_PRIMEIROS_SINTOMAS - VAG_DATA > 0 -- Evita casos em que a vacinacao ocorreu ante do inicio dos sintomas ou a vacinaÃ§Ã£o ocorreu no mesmo dia do inicio dos sintomas
    ORDER BY VAG_DATA
) A5 ON A1.CAS_ID = A5.CAS_ID
LEFT JOIN (
    SELECT 
        CAS_ID,
        CEV_DATE,
        CAS_DATA_PRIMEIROS_SINTOMAS,
        CEV_DATE - CAS_DATA_PRIMEIROS_SINTOMAS   AS DIAS_DO_CASO -- calculo da diferenÃ§a em dias
    FROM ( 
        SELECT
            CEV_CAS_ID,
            CEV_DATE
        FROM H_CASOS_EVOLUCOES
        UNION SELECT
            CEV_CAS_ID,
            CEV_DATE
        FROM CASOS_EVOLUCOES
    )  -- Retona o id do casos e a data da morte
    LEFT JOIN (SELECT CAS_ID, CAS_DATA_PRIMEIROS_SINTOMAS FROM H_CASOS UNION SELECT CAS_ID, CAS_DATA_PRIMEIROS_SINTOMAS FROM CASOS) -- Uso de usign para unir histÃ³rico com corrente
    ON CEV_CAS_ID = CAS_ID
) A6 ON A1.CAS_ID = A6.CAS_ID
LEFT JOIN (
    SELECT 
        CAS_ID, 
        COUNT(CAS_ID) AS QTD_VACINAS_COVID
    FROM (
        SELECT CAS_ID FROM (
            SELECT * FROM ( SELECT VAC_CAS_ID, VAC_DATA_APLICACAO FROM H_VACINAS_COVID UNION SELECT VAC_CAS_ID, VAC_DATA_APLICACAO FROM VACINAS_COVID )
            WHERE VAC_DATA_APLICACAO > '25/01/20' -- Impedir dados inconsistentes!
        ) -- Retona o id do casos e a data de sua ultima vacina
        LEFT JOIN (SELECT CAS_ID, CAS_DATA_PRIMEIROS_SINTOMAS FROM H_CASOS UNION SELECT CAS_ID, CAS_DATA_PRIMEIROS_SINTOMAS FROM CASOS) -- Uso de usign para unir histÃ³rico com corrente
        ON VAC_CAS_ID = CAS_ID
        WHERE CAS_DATA_PRIMEIROS_SINTOMAS - VAC_DATA_APLICACAO  > 0 -- Evita casos em que a vacinacao ocorreu ante do inicio dos sintomas ou a vacinaÃ§Ã£o ocorreu no mesmo dia do inicio dos sintomas
    ) GROUP BY CAS_ID
) A7 ON A1.CAS_ID = A7.CAS_ID
LEFT JOIN GENERO ON A1.CAS_GEN_ID = GENERO.GEN_ID
LEFT JOIN IDADES_GESTACIONAIS ON A1.CAS_IDG_ID = IDADES_GESTACIONAIS.IDG_ID
LEFT JOIN RACAS ON A1.CAS_RAC_ID = RACAS.RAC_ID
LEFT JOIN ESCOLARIDADES ON A1.CAS_ESC_ID = ESCOLARIDADES.ESC_ID
LEFT JOIN ZONAS ON A1.CAS_ZON_ID = ZONAS.ZON_ID
LEFT JOIN SUPORTE_VENTILADOR ON A1.CAS_SVE_ID = SVE_ID
LEFT JOIN CLASSIFICACOES ON A1.CAS_CLA_ID = CLA_ID
LEFT JOIN TRABALHA_ANIMAIS ON A1.CAS_TAN_ID = TAN_ID 
LEFT JOIN (
    SELECT 
        CEV_CAS_ID,
        EVO_DESC
    FROM (SELECT CEV_CAS_ID, CEV_EVO_ID FROM CASOS_EVOLUCOES UNION SELECT CEV_CAS_ID, CEV_EVO_ID FROM H_CASOS_EVOLUCOES) 
    LEFT JOIN EVOLUCOES ON CEV_EVO_ID = EVO_ID
) A8 ON A1.CAS_ID = A8.CEV_CAS_ID
LEFT JOIN (
    SELECT UTI_CAS_ID FROM UTI UNION SELECT UTI_CAS_ID FROM H_UTI
) A9 ON A1.CAS_ID = A9.UTI_CAS_ID
);