@tables/estados.sql
@tables/municipios.sql
@tables/unidades.sql
@tables/resultados_raiox.sql
@tables/evolucoes.sql
@tables/zonas.sql
@tables/aspectos_tomografia.sql
@tables/tipos_animais.sql
@tables/criterios_encerramento.sql
@tables/classificacoes.sql
@tables/antivirais_covid.sql
@tables/antivirais_gripe.sql
@tables/resultados_teste_antigeno.sql
@tables/resultados_teste_rtpcr.sql
@tables/tipos_testes_sorologicos.sql
@tables/tipos_amostras_sorologicas.sql
@tables/resultados_teste_sorologico.sql
@tables/tipos_amostra.sql
@tables/idades_gestacionais.sql
@tables/escolaridades.sql
@tables/suporte_ventilador.sql
@tables/genero.sql
@tables/doses.sql
@tables/sintomas.sql
@tables/comorbidades.sql
@tables/racas.sql
@tables/tipos_teste_antigeno.sql
@tables/virus_respiratorios.sql
COMMIT;