Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('1','Puérpera (até 45 dias do parto)');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('2','Doença Cardiovascular Crônica');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('3','Doença Hematológica Crônica');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('4','Síndrome de Down');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('5','Doença Hepática Crônica');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('6','Asma');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('7','Diabetes mellitus');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('8','Doença Neurológica Crônica');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('9','Outra Pneumopatia Crônica');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('10','Imunodeficiência/Imunodepressão');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('11','Doença Renal Crônica');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('12','Obesidade');
Insert into APP.COMORBIDADES (COM_ID,COM_NOME) values ('13','Outros');
