Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('1','Febre');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('2','Tosse');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('3','Dor de Garganta');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('4','Dispneia');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('5','Desconforto Respiratório');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('6','Saturação O2< 95%');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('7','Diarreia');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('8','Vômito');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('9','Dor abdominal');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('10','Fadiga');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('11','Perda do olfato');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('12','Perda do paladar');
Insert into APP.SINTOMAS (SIN_ID,SIN_NOME) values ('13','Outros');
